[package]
name = "nabi-secret"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
argon2 = { workspace = true }
aes-gcm = { workspace = true }
zeroize = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
keyring = { workspace = true }
