[package]
name = "nabi-ftp"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
nabi-i18n = { workspace = true }  # 에러 문구 3어화(trc, T8-1).
nabi-fs = { workspace = true }
async-trait = { workspace = true }
suppaftp = { workspace = true }
tokio = { workspace = true }
