[package]
name = "nabi-ssh-ext"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
nabi-proto = { workspace = true }
russh = { workspace = true }
tokio = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
bytes = { workspace = true }
